CREATE SCHEMA IF NOT EXISTS GAZETTER;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE GAZETTER.SOURCE (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(25) NOT NULL UNIQUE,
    DESCRIPTION text,
    INFO jsonb,
    CONSTRAINT PK_SOURCE PRIMARY KEY (ID)
);


CREATE TABLE GAZETTER.PLACE (
    ID BIGSERIAL NOT NULL,
    COUNTRY_CODE CHAR(2) NOT NULL,
    ADMIN1 CHAR(2),
    ADMIN2 text,
    GEOM geometry(Geometry,4326) NOT NULL,
    TYPE text,
    SUBTYPE text,
    RANK integer,
    SOURCE_ID bigint NOT NULL,
    SOURCE_KEY bigint,
    SOURCE_DATE integer,
    INFO jsonb,
    LAST_MODIFIED TIMESTAMP with time zone,
    CONSTRAINT PK_PLACE PRIMARY KEY (ID)
);


CREATE TABLE GAZETTER.NAME (
    ID BIGSERIAL NOT NULL,
    NAME text NOT NULL,
    UNAME text,
    LANGUAGE_CODE CHAR(3),
    TYPE integer NOT NULL,
    PLACE_ID bigint NOT NULL,
    SOURCE_ID bigint NOT NULL,
    SOURCE_KEY bigint,
    SOURCE_DATE integer,
    INFO jsonb,
    LAST_MODIFIED TIMESTAMP with time zone,
    CONSTRAINT PK_NAME PRIMARY KEY (ID)
);


CREATE TABLE GAZETTER.EDIT (
    ID BIGSERIAL NOT NULL,
    SUMMARY text NOT NULL,
    DETAILS text,
    INFO jsonb,
    START_DATE TIMESTAMP with time zone NOT NULL,
    END_DATE TIMESTAMP with time zone,
    CONSTRAINT PK_EDIT PRIMARY KEY (ID)
);


CREATE TABLE GAZETTER.CHANGE_REQUEST (
    ID BIGSERIAL NOT NULL,
    PLACE_ID bigint NOT NULL,
    INFO jsonb NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    LAST_MODIFIED TIMESTAMP with time zone,
    CONSTRAINT PK_CHANGE_REQUEST PRIMARY KEY (ID)
);



ALTER TABLE GAZETTER.PLACE ADD FOREIGN KEY (SOURCE_ID) REFERENCES GAZETTER.SOURCE(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE GAZETTER.NAME ADD FOREIGN KEY (PLACE_ID) REFERENCES GAZETTER.PLACE(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE GAZETTER.NAME ADD FOREIGN KEY (SOURCE_ID) REFERENCES GAZETTER.SOURCE(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE GAZETTER.CHANGE_REQUEST ADD FOREIGN KEY (PLACE_ID) REFERENCES GAZETTER.PLACE(ID)
    ON DELETE NO ACTION ON UPDATE NO ACTION;



CREATE INDEX IDX_PLACE_GEOM ON GAZETTER.PLACE USING GIST(GEOM);
CREATE INDEX IDX_PLACE_SOURCE ON GAZETTER.PLACE(SOURCE_ID);
CREATE INDEX IDX_NAME_PLACE ON GAZETTER.NAME(PLACE_ID);
CREATE INDEX IDX_NAME_SOURCE ON GAZETTER.NAME(SOURCE_ID);
CREATE INDEX IDX_CHANGE_REQUEST_PLACE ON GAZETTER.CHANGE_REQUEST(PLACE_ID);



CREATE OR REPLACE FUNCTION last_modified() RETURNS trigger AS $last_modified$
    BEGIN
        NEW.LAST_MODIFIED := current_timestamp;
        RETURN NEW;
    END;
$last_modified$ LANGUAGE plpgsql;



CREATE TRIGGER TGR_PLACE_UPDATE BEFORE INSERT OR UPDATE ON GAZETTER.PLACE
    FOR EACH ROW EXECUTE PROCEDURE last_modified();

CREATE TRIGGER TGR_NAME_UPDATE BEFORE INSERT OR UPDATE ON GAZETTER.NAME
    FOR EACH ROW EXECUTE PROCEDURE last_modified();

CREATE TRIGGER TGR_CHANGE_REQUEST_UPDATE BEFORE INSERT OR UPDATE ON GAZETTER.CHANGE_REQUEST
    FOR EACH ROW EXECUTE PROCEDURE last_modified();

