CREATE SCHEMA IF NOT EXISTS GAZETTEER;
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE GAZETTEER.SOURCE (
    ID BIGSERIAL NOT NULL,
    NAME VARCHAR(25) NOT NULL UNIQUE,
    DESCRIPTION varchar,
    INFO jsonb,
    CONSTRAINT PK_SOURCE PRIMARY KEY (ID)
);


CREATE TABLE GAZETTEER.PLACE (
    ID BIGSERIAL NOT NULL,
    COUNTRY_CODE CHAR(2) NOT NULL,
    ADMIN1 CHAR(2),
    ADMIN2 varchar,
    GEOM geometry(Geometry,4326) NOT NULL,
    TYPE varchar,
    SUBTYPE varchar,
    RANK integer,
    SOURCE_ID bigint NOT NULL,
    SOURCE_KEY bigint,
    SOURCE_DATE integer,
    INFO jsonb,
    CONSTRAINT PK_PLACE PRIMARY KEY (ID)
);


CREATE TABLE GAZETTEER.NAME (
    ID BIGSERIAL NOT NULL,
    NAME varchar NOT NULL,
    UNAME varchar NOT NULL,
    LANGUAGE_CODE CHAR(3),
    TYPE integer NOT NULL,
    PLACE_ID bigint NOT NULL,
    SOURCE_ID bigint NOT NULL,
    SOURCE_KEY bigint,
    SOURCE_DATE integer,
    INFO jsonb,
    CONSTRAINT PK_NAME PRIMARY KEY (ID)
);


CREATE TABLE GAZETTEER.EDIT (
    ID BIGSERIAL NOT NULL,
    SUMMARY varchar NOT NULL,
    DETAILS varchar,
    INFO jsonb,
    START_DATE TIMESTAMP with time zone NOT NULL,
    END_DATE TIMESTAMP with time zone,
    CONSTRAINT PK_EDIT PRIMARY KEY (ID)
);


CREATE TABLE GAZETTEER.CHANGE_REQUEST (
    ID BIGSERIAL NOT NULL,
    PLACE_ID bigint NOT NULL,
    INFO jsonb NOT NULL,
    STATUS VARCHAR(10) NOT NULL,
    LAST_MODIFIED TIMESTAMP with time zone,
    CONSTRAINT PK_CHANGE_REQUEST PRIMARY KEY (ID)
);



ALTER TABLE GAZETTEER.PLACE ADD FOREIGN KEY (SOURCE_ID) REFERENCES GAZETTEER.SOURCE(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE GAZETTEER.NAME ADD FOREIGN KEY (PLACE_ID) REFERENCES GAZETTEER.PLACE(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE GAZETTEER.NAME ADD FOREIGN KEY (SOURCE_ID) REFERENCES GAZETTEER.SOURCE(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;

ALTER TABLE GAZETTEER.CHANGE_REQUEST ADD FOREIGN KEY (PLACE_ID) REFERENCES GAZETTEER.PLACE(ID)
    ON DELETE CASCADE ON UPDATE NO ACTION;



CREATE INDEX IDX_PLACE_GEOM ON GAZETTEER.PLACE USING GIST(GEOM);
CREATE INDEX IDX_PLACE_SOURCE ON GAZETTEER.PLACE(SOURCE_ID);
CREATE INDEX IDX_NAME_PLACE ON GAZETTEER.NAME(PLACE_ID);
CREATE INDEX IDX_NAME_SOURCE ON GAZETTEER.NAME(SOURCE_ID);
CREATE INDEX IDX_CHANGE_REQUEST_PLACE ON GAZETTEER.CHANGE_REQUEST(PLACE_ID);



CREATE OR REPLACE FUNCTION last_modified() RETURNS trigger AS $last_modified$
    BEGIN
        NEW.LAST_MODIFIED := current_timestamp;
        RETURN NEW;
    END;
$last_modified$ LANGUAGE plpgsql;



CREATE TRIGGER TGR_CHANGE_REQUEST_UPDATE BEFORE INSERT OR UPDATE ON GAZETTEER.CHANGE_REQUEST
    FOR EACH ROW EXECUTE PROCEDURE last_modified();

